# Generated by Django 5.2.11 on 2026-02-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_id', models.IntegerField(db_index=True, unique=True)),
                ('ident', models.CharField(db_index=True, max_length=10, unique=True)),
                ('type', models.CharField(blank=True, max_length=40)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('latitude_deg', models.FloatField(blank=True, null=True)),
                ('longitude_deg', models.FloatField(blank=True, null=True)),
                ('elevation_ft', models.IntegerField(blank=True, null=True)),
                ('iso_country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('iso_region', models.CharField(blank=True, db_index=True, max_length=10)),
                ('municipality', models.CharField(blank=True, max_length=255)),
                ('iata_code', models.CharField(blank=True, db_index=True, max_length=3)),
                ('gps_code', models.CharField(blank=True, max_length=10)),
                ('local_code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_id', models.IntegerField(db_index=True, unique=True)),
                ('airport_ident', models.CharField(db_index=True, max_length=10)),
                ('length_ft', models.IntegerField(blank=True, null=True)),
                ('width_ft', models.IntegerField(blank=True, null=True)),
                ('surface', models.CharField(blank=True, max_length=50)),
                ('lighted', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('le_ident', models.CharField(blank=True, max_length=10)),
                ('le_latitude_deg', models.FloatField(blank=True, null=True)),
                ('le_longitude_deg', models.FloatField(blank=True, null=True)),
                ('he_ident', models.CharField(blank=True, max_length=10)),
                ('he_latitude_deg', models.FloatField(blank=True, null=True)),
                ('he_longitude_deg', models.FloatField(blank=True, null=True)),
                ('airport', models.ForeignKey(db_column='airport_fk_ident', on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='aviation.airport', to_field='ident')),
            ],
            options={
                'indexes': [models.Index(fields=['airport_ident', 'le_ident'], name='aviation_ru_airport_6d739a_idx'), models.Index(fields=['airport_ident', 'he_ident'], name='aviation_ru_airport_0bced5_idx')],
            },
        ),
    ]
