# Generated by Django 5.2.11 on 2026-02-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runway',
            name='surface',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
